#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "hanami/cli"

cli = Dry::CLI.new(Hanami::CLI)
Hanami::CLI::Bundler.require(:cli)

code = catch(:exit) {
  begin
    cli.call
    0
  rescue Hanami::CLI::Error => exception
    $stderr.puts(exception.message) # rubocop:disable Style/StderrPuts
    1
  end
}

exit(code)
